version: '3.3'
services:
  smtp:
    container_name: mailer-smtp
    image: bytemark/smtp
    restart: unless-stopped
  restapi:
    container_name: mailer-rest-api
    #image: ${DOCKER_REGISTRY-}mywebapi
    restart: unless-stopped
    build:
      context: .
      dockerfile: MailerRestApi/Dockerfile
    volumes:
      - "/data/Mailer/app/templates:/app/templates"
      - "/data/Mailer/app/meetings:/app/wwwroot/meetings"
    links:
      - smtp
    ports:
      - "127.0.0.1:5025:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TimerIntervalSeconds=$TimerIntervalSeconds
      - ServiceSecretsJson=$ServiceSecretsJson
      - FriendInfoDocumentId=$FriendInfoDocumentId
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
      - EmailFromName=$EmailFromName
      - EmailFromAddress=$EmailFromAddress
      - ScheduleViewSheet=$ScheduleViewSheet
      - ScheduleViewPublisherCell=A1
      - APPLICATIONINSIGHTS_INSTRUMENTATIONKEY=$APPLICATIONINSIGHTS_INSTRUMENTATIONKEY
      - APPLICATIONINSIGHTS_CONNECTION_STRING=$APPLICATIONINSIGHTS_CONNECTION_STRING
      - ScheduleGeneratorApiKey=$ScheduleGeneratorApiKey

