version: '3'
services:
  smtp:
    container_name: mailer-smtp
    image: bytemark/smtp
    restart: always
  restapi:
    container_name: mailer-rest-api
    #image: ${DOCKER_REGISTRY-}mywebapi
    build:
      context: .
      dockerfile: MailerRestApi/Dockerfile
    links:
      - smtp
    ports:
      - "5025:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TimerIntervalSeconds=$TimerIntervalSeconds
      - ServiceSecretsJson=$ServiceSecretsJson
      - ClmSendEmailsDocumentId=$ClmSendEmailsDocumentId
      - ClmAssignmentListDocumentId=$ClmAssignmentListDocumentId
      - Range=$Range
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
      - ScheduleViewSheet=CLM EMailer
      - ScheduleViewPublisherCell=A1
      - APPLICATIONINSIGHTS_INSTRUMENTATIONKEY=$APPLICATIONINSIGHTS_INSTRUMENTATIONKEY
      - APPLICATIONINSIGHTS_CONNECTION_STRING=$APPLICATIONINSIGHTS_CONNECTION_STRING

